name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Migrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Flyway CLI
      run: |
        wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.8.2/flyway-commandline-11.8.2-linux-x64.tar.gz
        tar -xzf flyway-commandline-11.8.2-linux-x64.tar.gz
        sudo ln -s `pwd`/flyway-11.8.2/flyway /usr/local/bin/flyway

    - name: Run Flyway migrate
      run: |
        flyway migrate \
          -url="${{ secrets.DB_URL }};encrypt=true;trustServerCertificate=true" \
          -user="${{ secrets.DB_USER }}" \
          -password="${{ secrets.DB_PASS }}" \
          -locations="filesystem:database/migrations" \
          -baselineOnMigrate=true


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          set -euo pipefail
          trap 'echo "❌ Deployment failed at command: $BASH_COMMAND"' ERR

          exec 5>&2
          exec 2>&1
          set -x
          
          echo "Changing to project directory"
          cd php-inventory-system/

          echo "Pulling latest code"
          git pull origin main

          echo "Deploying to /var/www/html"
          sudo systemctl restart nginx
          sudo cp -r . /var/www/html/inventory/

          echo "✅ Deployment completed successfully!"
